### PR TITLE
Rd 134 v1.4.0

### PR DESCRIPTION
**Pull request by chrispyatt**
static file references changed to 001_reference IDs, versions updated for eggd_nimagen_to_gel_vcf app and workflow

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_aphrodite_workflow/9)

### CODE REVIEW

**Review by mattgarner — COMMENTED** [review]
Files have not yet been relocated to 001 References, but project ids have been changed in the workflow in anticipation of this.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_aphrodite_workflow/9#-:-NSqGOvtEOTTAZA1s7ZO:b-deg76y)* status: 0 of 2 files reviewed, all discussions resolved

**Review by chrispyatt — COMMENTED** [review]
files are now in 001 in all cases (do we need to wait for that to be signed off before merging this?)

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_aphrodite_workflow/9#-:-NTZCEsn0bInAZHHv80V:b-pbhxkz)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by mattgarner — COMMENTED** [review]
001 files are now signed off, so moving ahead with this PR now

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_aphrodite_workflow/9#-:-NUSDmkj6e8bBvxVgkCO:b-3j3ri9)* status: 1 of 2 files reviewed, all discussions resolved

**Review by mattgarner — APPROVED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_aphrodite_workflow/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chrispyatt)

**Pull request merged**
